trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals devtest


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'

