trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals devtest

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        whoami
        sudo docker build --file Dockerfile --tag sample:1
        sudo docker images

